# Generated by Django 4.1.6 on 2023-03-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MealPlanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="customs_ingredients",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
