# Generated by Django 4.1.6 on 2023-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlanner', '0002_recipe_recipe_alter_recipe_customs_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
